<?php require('template/header.phtml');
?>
<html>
<div class="container">
    <div class="text-center">
        
    </div>

    <body>
        <div class="container">
            <?php if ($user->isLoggedIn()) : ?>
                <div class="jumbotron jumbotron-fluid mb-0">
                    <div class="container-fluid text-center ">
                        <h2>Can't find what you're looking for? Just search it!</h2>
                        <form action="../Search.php" class="form-inline justify-content-center" method="post">
                            <input class="form-control mr-sm-4" type="search" placeholder="Search" aria-label="Search" name="text">
                            <div class="input-group mr-sm-4">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="searchInField">Search In</label>
                                </div>
                                <select class="custom-select" id="searchInField" name="searchIn">
                                    <option value="1" selected>Buildings</option>
                                    <option value="2">Demographics</option>
                                    <option value="3">Utilities</option>
                                    <option value="4">Infrastructure</option>
                                </select>
                            </div>
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="search">Search</button>
                        </form>
                    </div>
                </div>
            <h3>Utilities</h3>
            <table class="table table-light">
                <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">id</th>
                    <th scope="col">postcode</th>
                    <th scope="col">name</th>
                    <th scope="col">type</th>
                    <th scope="col">classification</th>
                    <th scope="col">dependencies</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($view->utilities as $utility) : ?>
                <tr>
                    <th scope="row">1</th>
                    <td><?php echo $utility['_id']?></td>
                    <td><?php echo $utility['postcode']?></td>
                    <td><?php echo $utility['name']?></td>
                    <td><?php echo $utility['type']?></td>
                    <td><?php echo $utility['classification']?></td>
                    <td><?php foreach ($utility['dependencies'] as $dependency) { echo  $dependency;}?></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
                <h3> Demographics </h3>
                <table class="table table-light">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">postcode</th>
                        <th scope="col">Total Health Needs</th>
                        <th scope="col">Total Mobility Needs</th>
                        <th scope="col">Total Elderly</th>
                        <th scope="col">Total Population</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($view->demographics as $demographics) : ?>
                        <tr>
                            <th scope="row">1</th>
                            <td><?php echo $demographics['_id']?></td>
                            <td><?php echo $demographics['postcode']?></td>
                            <td><?php echo $demographics['totalHealthNeeds']?></td>
                            <td><?php echo $demographics['totalMobilityNeeds']?></td>
                            <td><?php echo $demographics['totalElderly']?></td>
                            <td><?php echo $demographics['totalPopulation']?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                </table>
            <h3> Buildings </h3>
                <table class="table table-light">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">name</th>
                        <th scope="col">type</th>
                        <th scope="col">postcode</th>
                        <th scope="col">city</th>
                        <th scope="col">size_m2</th>
                        <th scope="col">maxOccupants</th>
                        <th scope="col">value</th>
                        <th scope="col">id</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($view->buildings as $buildings) : ?>
                        <tr>
                            <th scope="row">1</th>
                            <td><?php echo $buildings['name']?></td>
                            <td><?php echo $buildings['type']?></td>
                            <td><?php echo $buildings['postcode']?></td>
                            <td><?php echo $buildings['city']?></td>
                            <td><?php echo $buildings['size_m2']?></td>
                            <td><?php echo $buildings['maxOccupants']?></td>
                            <td><?php echo $buildings['value']?></td>
                            <td><?php echo $buildings['_id']?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                </table>
                <h3> Infrastructures </h3>
                <table class="table table-light">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">Type</th>
                        <th scope="col">Name</th>
                        <th scope="col">Classification</th>
                        <th scope="col">Area codes</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($view->infrastructure as $infrastructure) : ?>
                        <tr>
                            <th scope="row">1</th>
                            <td><?php echo $infrastructure['_id']?></td>
                            <td><?php echo $infrastructure['type']?></td>
                            <td><?php echo $infrastructure['name']?></td>
                            <td><?php echo $infrastructure['classification']?></td>
                            <td><?php foreach ($infrastructure['postcodes'] as $postcodes) { echo  $postcodes.' / ';}?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </body>


</html>

<?php require('template/footer.phtml') ?>