<?php
require('template/header.phtml') ?>
<div class="container">
    <h3> Demographics </h3>
    <table class="table table-light">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Id</th>
            <th scope="col">postcode</th>
            <th scope="col">Total Health Needs</th>
            <th scope="col">Total Mobility Needs</th>
            <th scope="col">Total Elderly</th>
            <th scope="col">Total Population</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($view->dataSet as $demographics) : ?>
            <tr>
                <th scope="row">1</th>
                <td><?php echo $demographics->getId();?></td>
                <td><?php echo $demographics->getPostcode();?></td>
                <td><?php echo $demographics->getTotalHealthNeeds();?></td>
                <td><?php echo $demographics->getTotalMobilityNeeds();?></td>
                <td><?php echo $demographics->getTotalElderly();?></td>
                <td><?php echo $demographics->getTotalPopulation();?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php require ('template/footer.phtml') ?>
